version: '3.8' 

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mariadb

  php:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: codeigniter_db
      MYSQL_USER: codeigniter_user
      MYSQL_PASSWORD: your_user_password
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
